### ISSUE TITLE
Collect Julia's GH Hive NYC curriculum

### ISSUE THREAD

**Issue by chrislarry33** [MozillaHive/HiveCreate#1]
Hi Julia,

RACI

Rassponsible: @jvallera 
Acountable: @chrislarry33
Consulted: @leahatplay @ldecoursy @laurahilliger
Informed: @simonaramkisson, @mcdermott415 @thornet
Quality: @chrislarry33

(Below same copy as email)

Julia-
Can you collect all the curriculum/PD activities, resources and related blog posts you helped to create and curate for
- TASC/TASCasaurus
- PACE Brooklyn Explorers
- PACE Explores 
- Maker ED/DOE teacher interns
- IPPD

Here is etherpad https://hive.etherpad.mozilla.org/JuliaGH

I know there is a lot of good pieces in here that we can identify, update, polish and use. It has been very informative for us to be looking back over the last years and pulling up Greatest Hits to be featured on the new teach.mozilla.org. The above projects can contribute to web literacy activities, teaching the mozilla way and example assets of featured partnerships.

**Comment by jvallera** [comment]
Is there a deadline for this? Need some time to dig up everything and filter notes from content.

**Comment by LauraHilliger** [comment]
If you could do during this heartbeat (ends March 27) that would be super helpful!

**Comment by chrislarry33** [comment]
Is two weeks doable?

**Comment by jvallera** [comment]
Yes. Will complete by March 24. Placing everything in Etherpad for now.

**Comment by chrislarry33** [comment]
This is awesome @jvallera thanks a ton. So much good stuff here. @LauraHilliger does this all make sense from a cataloging perspective

**Comment by mcdermott415** [comment]
this is great - very useful as a set of materials to demonstrate train the trainer and pd expertise

**Comment by LauraHilliger** [comment]
@jvallera excellent! There's loads in here we can pull into "best of" teaching kits, and the train the trainer agendas provide a huge body of examples and practices we can pull into Teach Like Mozilla – loads of ideas floating around :bulb:  

I couldn't access the PASE Internal agenda:

https://docs.google.com/a/pasesetter.org/document/d/1bTAZ954_3xBJPpLeVW4E5Phu8_FoS3djpMUV4cyGYHs/edit?usp=sharing

can you open that one up? 

Just as a heads up, I noticed you're still (well in 2013) using http://hivenyc.org/kits.html – but all that content has been revised and moved. You can find the Storycamp kits here:

https://mozteach.makes.org/thimble/storycamp-resources

and other kits are either here: https://webmaker.org/en-US/user/mozteach/teaching-resources
or here: https://webmaker.org/en-US/user/laura/teaching-resources

Thank you, thank you – this is great.

**Comment by jvallera** [comment]
@LauraHilliger great! glad it is helpful. If anything else is not clear/not working let me know. I changed the access for PASE internal agenda. Thanks for the mozteach reminder. I forget where stuff is sometimes ;)
